version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}apiexample
    build:
      context: .
      dockerfile: API_Example/Dockerfile

  client:
    image: client
    build:
        context: ./example-client
        dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

  postgres:
    container_name: postgres_container
    image: postgres


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4

  prometheus:
    image: prom/prometheus

  node-exporter:
    image: prom/node-exporter

  grafana:
    image: grafana/grafana
  
  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.1
















